name: Publish
on:
  pull_request:
    paths:
      - "index*.ts"
      - "test/**"
      - ".github/workflows/publish.yml"
      - "package.json"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "index.ts"
      - "README.md"
      - ".github/workflows/publish.yml"
      - "package.json"
    tags:
      - "v*"
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      TAG_BRANCH: ${{ env.TAG_BRANCH_NAME }}
      SHORT_SHA: ${{ env.SHORT_SHA }}
      TAGGED: ${{ env.TAGGED }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: prepare_env
        run: |
          echo "TAGGED=${{ startsWith(github.ref, 'refs/tags/v') }}" >> $GITHUB_ENV
          
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          echo "$SHORT_SHA"
          echo "$GITHUB_REF"
          echo "$GITHUB_REF_NAME"

          RAW=$(git branch -r --contains $SHORT_SHA)
          TAG_BRANCH_NAME="${RAW##*/}"
          echo "TAG_BRANCH_NAME=$TAG_BRANCH_NAME" >> $GITHUB_ENV

      - run: echo "${{ toJSON(env) }}"

  test:
    name: test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16
          - 18
          - 20
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - uses: borales/actions-yarn@v4
        with:
          cmd: tsd

      - uses: borales/actions-yarn@v4
        with:
          cmd: test

      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: lib

  publish:
    name: Publish to npmjs
    runs-on: ubuntu-latest
    needs: [prepare, test]
    if: ${{ needs.prepare.outputs.TAG_BRANCH == 'main' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      
      - uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib
      
      - uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ./lib/**

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          create_branch: true
          branch: "changelog-${{ github.run_id }}"
